language: php
php:
  - '5.6'
  - '7.2'

services:
  - mysql

# 项目所在分支
branches:
  only:
  - master

before_install:
  - mysql -e 'CREATE DATABASE twinkle_test;'

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover


